--
-- PostgreSQL database dump
--

-- Dumped from database version 15.2
-- Dumped by pg_dump version 15.2

-- Started on 2023-03-06 09:41:43

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE hibernate_demo;
--
-- TOC entry 3378 (class 1262 OID 16531)
-- Name: hibernate_demo; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE hibernate_demo WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'Ukrainian_Ukraine.1251';


ALTER DATABASE hibernate_demo OWNER TO postgres;

\connect hibernate_demo

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 221 (class 1259 OID 16587)
-- Name: actor; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.actor (
    id integer NOT NULL,
    name character varying(100) NOT NULL,
    age integer,
    CONSTRAINT actor_age_check CHECK ((age > 0))
);


ALTER TABLE public.actor OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16586)
-- Name: actor_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.actor ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.actor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16602)
-- Name: actor_movie; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.actor_movie (
    actor_id integer NOT NULL,
    movie_id integer NOT NULL
);


ALTER TABLE public.actor_movie OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16553)
-- Name: item; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.item (
    id integer NOT NULL,
    person_id integer,
    name character varying(100) NOT NULL
);


ALTER TABLE public.item OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 16552)
-- Name: item_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 16596)
-- Name: movie; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.movie (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    year_of_production integer,
    CONSTRAINT movie_year_of_production_check CHECK ((year_of_production > 1900))
);


ALTER TABLE public.movie OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 16595)
-- Name: movie_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.movie ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.movie_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 16574)
-- Name: passport; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.passport (
    id integer NOT NULL,
    passport_number integer NOT NULL,
    person_id integer
);


ALTER TABLE public.passport OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 16573)
-- Name: passport_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.passport ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.passport_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 16546)
-- Name: person; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.person (
    id integer NOT NULL,
    name character varying(100) NOT NULL,
    age integer,
    CONSTRAINT person_age_check CHECK ((age < 100))
);


ALTER TABLE public.person OWNER TO postgres;

--
-- TOC entry 214 (class 1259 OID 16545)
-- Name: person_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.person ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.person_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3369 (class 0 OID 16587)
-- Dependencies: 221
-- Data for Name: actor; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.actor (id, name, age) VALUES (1, 'Harvey Keitel', 81);
INSERT INTO public.actor (id, name, age) VALUES (2, 'Samuel L. Jackson', 72);


--
-- TOC entry 3372 (class 0 OID 16602)
-- Dependencies: 224
-- Data for Name: actor_movie; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.actor_movie (actor_id, movie_id) VALUES (1, 1);
INSERT INTO public.actor_movie (actor_id, movie_id) VALUES (1, 2);


--
-- TOC entry 3365 (class 0 OID 16553)
-- Dependencies: 217
-- Data for Name: item; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.item (id, person_id, name) VALUES (2, 1, 'AirPods');
INSERT INTO public.item (id, person_id, name) VALUES (8, 4, 'Item from app2');
INSERT INTO public.item (id, person_id, name) VALUES (3, NULL, 'Iphone');
INSERT INTO public.item (id, person_id, name) VALUES (7, NULL, 'Item from app');
INSERT INTO public.item (id, person_id, name) VALUES (1, 4, 'Book');
INSERT INTO public.item (id, person_id, name) VALUES (11, 8, 'Test cascading item');
INSERT INTO public.item (id, person_id, name) VALUES (12, 9, 'Item 1');
INSERT INTO public.item (id, person_id, name) VALUES (13, 9, 'Item 2');
INSERT INTO public.item (id, person_id, name) VALUES (14, 9, 'Item 3');


--
-- TOC entry 3371 (class 0 OID 16596)
-- Dependencies: 223
-- Data for Name: movie; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.movie (id, name, year_of_production) VALUES (1, 'Pulp fiction', 1994);
INSERT INTO public.movie (id, name, year_of_production) VALUES (2, 'Reservoir Dogs', 1992);


--
-- TOC entry 3367 (class 0 OID 16574)
-- Dependencies: 219
-- Data for Name: passport; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.passport (id, passport_number, person_id) VALUES (1, 4235, 1);


--
-- TOC entry 3363 (class 0 OID 16546)
-- Dependencies: 215
-- Data for Name: person; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.person (id, name, age) VALUES (1, 'Tom', 35);
INSERT INTO public.person (id, name, age) VALUES (3, 'Jack', 19);
INSERT INTO public.person (id, name, age) VALUES (4, 'Test person', 23);
INSERT INTO public.person (id, name, age) VALUES (8, 'Test cascading', 30);
INSERT INTO public.person (id, name, age) VALUES (9, 'Test cascading', 30);


--
-- TOC entry 3379 (class 0 OID 0)
-- Dependencies: 220
-- Name: actor_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.actor_id_seq', 2, true);


--
-- TOC entry 3380 (class 0 OID 0)
-- Dependencies: 216
-- Name: item_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.item_id_seq', 14, true);


--
-- TOC entry 3381 (class 0 OID 0)
-- Dependencies: 222
-- Name: movie_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.movie_id_seq', 2, true);


--
-- TOC entry 3382 (class 0 OID 0)
-- Dependencies: 218
-- Name: passport_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.passport_id_seq', 1, true);


--
-- TOC entry 3383 (class 0 OID 0)
-- Dependencies: 214
-- Name: person_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.person_id_seq', 10, true);


--
-- TOC entry 3215 (class 2606 OID 16606)
-- Name: actor_movie actor_movie_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.actor_movie
    ADD CONSTRAINT actor_movie_pkey PRIMARY KEY (actor_id, movie_id);


--
-- TOC entry 3209 (class 2606 OID 16594)
-- Name: actor actor_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.actor
    ADD CONSTRAINT actor_name_key UNIQUE (name);


--
-- TOC entry 3211 (class 2606 OID 16592)
-- Name: actor actor_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.actor
    ADD CONSTRAINT actor_pkey PRIMARY KEY (id);


--
-- TOC entry 3203 (class 2606 OID 16557)
-- Name: item item_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.item
    ADD CONSTRAINT item_pkey PRIMARY KEY (id);


--
-- TOC entry 3213 (class 2606 OID 16601)
-- Name: movie movie_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.movie
    ADD CONSTRAINT movie_pkey PRIMARY KEY (id);


--
-- TOC entry 3205 (class 2606 OID 16580)
-- Name: passport passport_person_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.passport
    ADD CONSTRAINT passport_person_id_key UNIQUE (person_id);


--
-- TOC entry 3207 (class 2606 OID 16578)
-- Name: passport passport_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.passport
    ADD CONSTRAINT passport_pkey PRIMARY KEY (id);


--
-- TOC entry 3201 (class 2606 OID 16551)
-- Name: person person_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.person
    ADD CONSTRAINT person_pkey PRIMARY KEY (id);


--
-- TOC entry 3218 (class 2606 OID 16607)
-- Name: actor_movie actor_movie_actor_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.actor_movie
    ADD CONSTRAINT actor_movie_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES public.actor(id);


--
-- TOC entry 3219 (class 2606 OID 16612)
-- Name: actor_movie actor_movie_movie_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.actor_movie
    ADD CONSTRAINT actor_movie_movie_id_fkey FOREIGN KEY (movie_id) REFERENCES public.movie(id);


--
-- TOC entry 3216 (class 2606 OID 16558)
-- Name: item item_person_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.item
    ADD CONSTRAINT item_person_id_fkey FOREIGN KEY (person_id) REFERENCES public.person(id) ON DELETE SET NULL;


--
-- TOC entry 3217 (class 2606 OID 16581)
-- Name: passport passport_person_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.passport
    ADD CONSTRAINT passport_person_id_fkey FOREIGN KEY (person_id) REFERENCES public.person(id) ON DELETE CASCADE;


-- Completed on 2023-03-06 09:41:44

--
-- PostgreSQL database dump complete
--

